<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <StartupObject>VENM.App</StartupObject>
    <AssemblyName>$(MSBuildVENM)</AssemblyName>
    <RootNamespace>$(MSBuildVENM.Replace(" ", "_"))</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\VENMLibrary\VENMLibrary.csproj" />
  </ItemGroup>

</Project>