using System.Collections.Generic;

namespace VENMLibrary
{
    public enum AppLanguage { Ru, En, Zh, Ar, Hi, It, Fr, De }

    public static class UILocalization
    {
        private static readonly Dictionary<string, Dictionary<AppLanguage, string>> _s = new()
        {
            ["WindowTitle"] = new() { [AppLanguage.Ru] = "Визуальный Редактор Файлов", [AppLanguage.En] = "Visual File Editor", [AppLanguage.Zh] = "可视化文件编辑器", [AppLanguage.Ar] = "محرر الملفات المرئي", [AppLanguage.Hi] = "दृश्य फ़ाइल संपादक", [AppLanguage.It] = "Editor di file visivo", [AppLanguage.Fr] = "Éditeur de fichiers visuel", [AppLanguage.De] = "Visueller Dateieditor" },
            ["LblLanguage"] = new() { [AppLanguage.Ru] = "Язык", [AppLanguage.En] = "Language", [AppLanguage.Zh] = "语言", [AppLanguage.Ar] = "اللغة", [AppLanguage.Hi] = "भाषा", [AppLanguage.It] = "Lingua", [AppLanguage.Fr] = "Langue", [AppLanguage.De] = "Sprache" },
            ["LblEditMode"] = new() { [AppLanguage.Ru] = "Режим редактирования", [AppLanguage.En] = "Edit mode", [AppLanguage.Zh] = "编辑模式", [AppLanguage.Ar] = "وضع التحرير", [AppLanguage.Hi] = "संपादन मोड", [AppLanguage.It] = "Modalità di modifica", [AppLanguage.Fr] = "Mode d'édition", [AppLanguage.De] = "Bearbeitungsmodus" },
            ["LblScene"] = new() { [AppLanguage.Ru] = "Сцена", [AppLanguage.En] = "Scene", [AppLanguage.Zh] = "场景", [AppLanguage.Ar] = "المشهد", [AppLanguage.Hi] = "दृश्य", [AppLanguage.It] = "Scena", [AppLanguage.Fr] = "Scène", [AppLanguage.De] = "Szene" },
            ["LblObject"] = new() { [AppLanguage.Ru] = "Объект", [AppLanguage.En] = "Object", [AppLanguage.Zh] = "对象", [AppLanguage.Ar] = "الكائن", [AppLanguage.Hi] = "वस्तु", [AppLanguage.It] = "Oggetto", [AppLanguage.Fr] = "Objet", [AppLanguage.De] = "Objekt" },
            ["LblFile"] = new() { [AppLanguage.Ru] = "Файл", [AppLanguage.En] = "File", [AppLanguage.Zh] = "文件", [AppLanguage.Ar] = "الملف", [AppLanguage.Hi] = "फ़ाइल", [AppLanguage.It] = "File", [AppLanguage.Fr] = "Fichier", [AppLanguage.De] = "Datei" },
            ["BtnOpenAssets"] = new() { [AppLanguage.Ru] = "Открыть ресурсы", [AppLanguage.En] = "Open resources", [AppLanguage.Zh] = "打开资源", [AppLanguage.Ar] = "فتح الموارد", [AppLanguage.Hi] = "संसाधन खोलें", [AppLanguage.It] = "Apri risorse", [AppLanguage.Fr] = "Ouvrir les ressources", [AppLanguage.De] = "Ressourcen öffnen" },
            ["BtnCreateDemo"] = new() { [AppLanguage.Ru] = "Создать демо-структуру", [AppLanguage.En] = "Create demo structure", [AppLanguage.Zh] = "创建演示结构", [AppLanguage.Ar] = "إنشاء بنية تجريبية", [AppLanguage.Hi] = "डेमो संरचना बनाएँ", [AppLanguage.It] = "Crea struttura demo", [AppLanguage.Fr] = "Créer la structure démo", [AppLanguage.De] = "Demo-Struktur erstellen" },
            ["BtnSave"] = new() { [AppLanguage.Ru] = "Сохранить", [AppLanguage.En] = "Save", [AppLanguage.Zh] = "保存", [AppLanguage.Ar] = "حفظ", [AppLanguage.Hi] = "सहेजें", [AppLanguage.It] = "Salva", [AppLanguage.Fr] = "Enregistrer", [AppLanguage.De] = "Speichern" },
            ["ChkAutoSave"] = new() { [AppLanguage.Ru] = "Автосохранение", [AppLanguage.En] = "Auto-save", [AppLanguage.Zh] = "自动保存", [AppLanguage.Ar] = "حفظ تلقائي", [AppLanguage.Hi] = "स्वतः सहेजना", [AppLanguage.It] = "Salvataggio automatico", [AppLanguage.Fr] = "Sauvegarde automatique", [AppLanguage.De] = "Automatische Speicherung" },
            ["ChkHideObject"] = new() { [AppLanguage.Ru] = "Скрыть объект", [AppLanguage.En] = "Hide object", [AppLanguage.Zh] = "隐藏对象", [AppLanguage.Ar] = "إخفاء الكائن", [AppLanguage.Hi] = "वस्तु छिपाएँ", [AppLanguage.It] = "Nascondi oggetto", [AppLanguage.Fr] = "Masquer l'objet", [AppLanguage.De] = "Objekt ausblenden" },
            ["ModeScene"] = new() { [AppLanguage.Ru] = "Редактор Сцены", [AppLanguage.En] = "Scene Editor", [AppLanguage.Zh] = "场景编辑器", [AppLanguage.Ar] = "محرر المشهد", [AppLanguage.Hi] = "दृश्य संपादक", [AppLanguage.It] = "Editor scena", [AppLanguage.Fr] = "Éditeur de scène", [AppLanguage.De] = "Szeneneditor" },
            ["ModeObject"] = new() { [AppLanguage.Ru] = "Редактор Объекта", [AppLanguage.En] = "Object Editor", [AppLanguage.Zh] = "对象编辑器", [AppLanguage.Ar] = "محرر الكائن", [AppLanguage.Hi] = "वस्तु संपादक", [AppLanguage.It] = "Editor oggetto", [AppLanguage.Fr] = "Éditeur d'objet", [AppLanguage.De] = "Objekteditor" },
            ["ModeFont"] = new() { [AppLanguage.Ru] = "Редактор Шрифтов", [AppLanguage.En] = "Font Editor", [AppLanguage.Zh] = "字体编辑器", [AppLanguage.Ar] = "محرر الخطوط", [AppLanguage.Hi] = "फ़ॉन्ट संपादक", [AppLanguage.It] = "Editor caratteri", [AppLanguage.Fr] = "Éditeur de polices", [AppLanguage.De] = "Schriftarteneditor" },
            ["MsgSuccess"] = new() { [AppLanguage.Ru] = "Успех", [AppLanguage.En] = "Success", [AppLanguage.Zh] = "成功", [AppLanguage.Ar] = "نجاح", [AppLanguage.Hi] = "सफलता", [AppLanguage.It] = "Successo", [AppLanguage.Fr] = "Succès", [AppLanguage.De] = "Erfolg" },
            ["MsgError"] = new() { [AppLanguage.Ru] = "Ошибка", [AppLanguage.En] = "Error", [AppLanguage.Zh] = "错误", [AppLanguage.Ar] = "خطأ", [AppLanguage.Hi] = "त्रुटि", [AppLanguage.It] = "Errore", [AppLanguage.Fr] = "Erreur", [AppLanguage.De] = "Fehler" },
            ["MsgFileSaved"] = new() { [AppLanguage.Ru] = "Файл успешно сохранён!", [AppLanguage.En] = "File saved successfully!", [AppLanguage.Zh] = "文件保存成功！", [AppLanguage.Ar] = "تم حفظ الملف بنجاح!", [AppLanguage.Hi] = "फ़ाइल सफलतापूर्वक सहेजी गई!", [AppLanguage.It] = "File salvato con successo!", [AppLanguage.Fr] = "Fichier enregistré avec succès !", [AppLanguage.De] = "Datei erfolgreich gespeichert!" },
            ["MsgFileClosed"] = new() { [AppLanguage.Ru] = "Файл не открыт.\nВыберите файл из списка для начала работы.", [AppLanguage.En] = "No file is open.\nSelect a file from the list to start.", [AppLanguage.Zh] = "未打开文件。\n请从列表中选择一个文件以开始。", [AppLanguage.Ar] = "لا يوجد ملف مفتوح.\nحدد ملفًا من القائمة للبدء.", [AppLanguage.Hi] = "कोई फ़ाइल खुली नहीं है।\nशुरू करने के लिए सूची से फ़ाइल चुनें।", [AppLanguage.It] = "Nessun file aperto.\nSeleziona un file dall'elenco per iniziare.", [AppLanguage.Fr] = "Aucun fichier ouvert.\nSélectionnez un fichier dans la liste pour commencer.", [AppLanguage.De] = "Keine Datei geöffnet.\nWählen Sie eine Datei aus der Liste aus, um zu beginnen." },
            ["MsgSceneNotSelected"] = new() { [AppLanguage.Ru] = "Сцена не выбрана", [AppLanguage.En] = "No scene selected", [AppLanguage.Zh] = "未选择场景", [AppLanguage.Ar] = "لم يتم اختيار مشهد", [AppLanguage.Hi] = "कोई दृश्य चयनित नहीं", [AppLanguage.It] = "Nessuna scena selezionata", [AppLanguage.Fr] = "Aucune scène sélectionnée", [AppLanguage.De] = "Keine Szene ausgewählt" },
            ["MsgFontModeNoPreview"] = new() { [AppLanguage.Ru] = "Просмотр сцены недоступен в режиме шрифтов", [AppLanguage.En] = "Scene preview unavailable in font mode", [AppLanguage.Zh] = "字体模式下无法预览场景", [AppLanguage.Ar] = "معاينة المشهد غير متاحة في وضع الخطوط", [AppLanguage.Hi] = "फ़ॉन्ट मोड में दृश्य पूर्वावलोकन उपलब्ध नहीं", [AppLanguage.It] = "Anteprima scena non disponibile in modalità caratteri", [AppLanguage.Fr] = "Aperçu de scène indisponible en mode polices", [AppLanguage.De] = "Szenenvorschau im Schriftartenmodus nicht verfügbar" },
            ["MsgSelectSceneFirst"] = new() { [AppLanguage.Ru] = "Сначала выберите сцену!", [AppLanguage.En] = "Please select a scene first!", [AppLanguage.Zh] = "请先选择场景！", [AppLanguage.Ar] = "يرجى اختيار مشهد أولاً!", [AppLanguage.Hi] = "पहले एक दृश्य चुनें!", [AppLanguage.It] = "Seleziona prima una scena!", [AppLanguage.Fr] = "Veuillez d'abord sélectionner une scène !", [AppLanguage.De] = "Bitte wählen Sie zuerst eine Szene aus!" },
            ["MsgDemoNotLoaded"] = new() { [AppLanguage.Ru] = "Демо-структура не загружена.\nНажмите 'Создать демо-структуру' для просмотра примеров.", [AppLanguage.En] = "Demo structure not loaded.\nClick 'Create demo structure' to view examples.", [AppLanguage.Zh] = "演示结构未加载。\n点击'创建演示结构'查看示例。", [AppLanguage.Ar] = "لم يتم تحميل البنية التجريبية.\nانقر فوق 'إنشاء بنية تجريبية' لعرض الأمثلة.", [AppLanguage.Hi] = "डेमो संरचना लोड नहीं हुई।\nउदाहरण देखने के लिए 'डेमो संरचना बनाएँ' पर क्लिक करें।", [AppLanguage.It] = "Struttura demo non caricata.\nFare clic su 'Crea struttura demo' per visualizzare gli esempi.", [AppLanguage.Fr] = "Structure démo non chargée.\nCliquez sur 'Créer la structure démo' pour voir les exemples.", [AppLanguage.De] = "Demo-Struktur nicht geladen.\nKlicken Sie auf 'Demo-Struktur erstellen', um Beispiele anzuzeigen." },
            ["CtxCreateScene"] = new() { [AppLanguage.Ru] = "Создать сцену", [AppLanguage.En] = "Create scene", [AppLanguage.Zh] = "创建场景", [AppLanguage.Ar] = "إنشاء مشهد", [AppLanguage.Hi] = "दृश्य बनाएँ", [AppLanguage.It] = "Crea scena", [AppLanguage.Fr] = "Créer une scène", [AppLanguage.De] = "Szene erstellen" },
            ["CtxCreateObject"] = new() { [AppLanguage.Ru] = "Создать объект", [AppLanguage.En] = "Create object", [AppLanguage.Zh] = "创建对象", [AppLanguage.Ar] = "إنشاء كائن", [AppLanguage.Hi] = "वस्तु बनाएँ", [AppLanguage.It] = "Crea oggetto", [AppLanguage.Fr] = "Créer un objet", [AppLanguage.De] = "Objekt erstellen" },
            ["CtxAddFont"] = new() { [AppLanguage.Ru] = "Добавить шрифт", [AppLanguage.En] = "Add font", [AppLanguage.Zh] = "添加字体", [AppLanguage.Ar] = "إضافة خط", [AppLanguage.Hi] = "फ़ॉन्ट जोड़ें", [AppLanguage.It] = "Aggiungi carattere", [AppLanguage.Fr] = "Ajouter une police", [AppLanguage.De] = "Schriftart hinzufügen" },
            ["CtxDeleteScene"] = new() { [AppLanguage.Ru] = "Удалить сцену", [AppLanguage.En] = "Delete scene", [AppLanguage.Zh] = "删除场景", [AppLanguage.Ar] = "حذف مشهد", [AppLanguage.Hi] = "दृश्य हटाएँ", [AppLanguage.It] = "Elimina scena", [AppLanguage.Fr] = "Supprimer la scène", [AppLanguage.De] = "Szene löschen" },
            ["CtxDeleteObject"] = new() { [AppLanguage.Ru] = "Удалить объект", [AppLanguage.En] = "Delete object", [AppLanguage.Zh] = "删除对象", [AppLanguage.Ar] = "حذف كائن", [AppLanguage.Hi] = "वस्तु हटाएँ", [AppLanguage.It] = "Elimina oggetto", [AppLanguage.Fr] = "Supprimer l'objet", [AppLanguage.De] = "Objekt löschen" },
            ["CtxDeleteFont"] = new() { [AppLanguage.Ru] = "Удалить шрифт", [AppLanguage.En] = "Delete font", [AppLanguage.Zh] = "删除字体", [AppLanguage.Ar] = "حذف خط", [AppLanguage.Hi] = "फ़ॉन्ट हटाएँ", [AppLanguage.It] = "Elimina carattere", [AppLanguage.Fr] = "Supprimer la police", [AppLanguage.De] = "Schriftart löschen" },
            ["CtxRename"] = new() { [AppLanguage.Ru] = "Переименовать", [AppLanguage.En] = "Rename", [AppLanguage.Zh] = "重命名", [AppLanguage.Ar] = "إعادة تسمية", [AppLanguage.Hi] = "नाम बदलें", [AppLanguage.It] = "Rinomina", [AppLanguage.Fr] = "Renommer", [AppLanguage.De] = "Umbenennen" }
        };

        public static string Get(string key, AppLanguage lang)
            => _s.TryGetValue(key, out var langs) && langs.TryGetValue(lang, out var val) ? val : key;

        public static bool IsRtl(AppLanguage lang) => lang == AppLanguage.Ar;
    }
}